### PR TITLE
changed base docker image to be from the jboss community centOS images

### PR DESCRIPTION
**Pull request by vbusch**

### CODE REVIEW

**Comment by vbusch** [comment]
I noticed the tests pulled the image from:
repository: docker.io/redhat-openjdk-18/openjdk18-openshift

It would be best, if it was pulled from:
repository: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift

How many projects use travis-ci.org?  Can we add another a few more registries into docker on that box?

I am not sure if the repository is responsible for the test failure.  The tests do pass, when I run them on ce-devel.usersys.redhat.com.  I think it would be good to try getting the redhat repositories into the docker configs.

**Comment by lulf** [comment]
We should use images available on docker hub and not require anyone to modify their docker config in order to build.

Also, can you deploy and use this  base image without subscriptions?

I would prefer if this was centos-based.

**Comment by ppatierno** [comment]
Totally agree with @lulf

**Comment by lulf** [comment]
@vbusch Thanks!

**Pull request merged**
